### ISSUE TITLE
crash w/ branch 0.27.0

### ISSUE THREAD

**Issue by jaz-ah** [BranchMetrics/ios-branch-deep-linking-attribution#918]
looks like you guys tried to make a fix in this area before - we're seeing many crashes in this area via crashlytics (no reproducible steps):

#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000066a6f56b0 Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 16
1 | Branch | BNCEncodingUtils.m line 145+[BNCEncodingUtils sanitizedStringFromString:]
2 | Branch | BNCEncodingUtils.m line 208+[BNCEncodingUtils encodeDictionaryToJsonString:]
3 | Branch | BNCEncodingUtils.m line 185+[BNCEncodingUtils encodeDictionaryToJsonString:]
4 | Branch | BNCEncodingUtils.m line 159+[BNCEncodingUtils encodeDictionaryToJsonData:]
5 | Branch | BNCServerInterface.m line 777-[BNCServerInterface preparePostRequest:url:key:retryNumber:]
6 | Branch | BNCServerInterface.m line 567__75-[BNCServerInterface genericHTTPRequest:retryNumber:callback:retryHandler:]_block_invoke_2
7 | libdispatch.dylib | _dispatch_call_block_and_release + 24
14 | UIKitCore | UIApplicationMain + 212

**Comment by echo-branch** [comment]
Thanks for bringing this to my attention.  I believe the issue is an unexpected key type is making it all the way to serialization.  I put in some protection around it and merged it to staging.

**Comment by jaz-ah** [comment]
thanks @echo-branch - what is your ETA to getting this into a released sdk?

**Comment by csalmi-branch** [comment]
We will hopefully be releasing a new version of the SDK in our next sprint cycle.

**Comment by leandromperez** [comment]
👍 waiting for the fix here too!

**Comment by jaz-ah** [comment]
@csalmi-branch is the fix in the 0.27.1 release?

**Comment by csalmi-branch** [comment]
Yes! Sorry about the delay in notification. The fix has been released in v0.27.1 which is now available.

**Comment by LucasVanDongen** [comment]
I'm still experiencing these crashes after updating to 0.27.1. I have no idea what strings cause them so I have no idea what to test against to begin with.

**Comment by echo-branch** [comment]
@LucasVanDongen  We only log the unexpected type, but not the actual value.  In the previous example, the issue was passing an NSNumber as a custom key instead of a NSString.  Are you seeing exactly the same crash log?  Maybe there's another location where an invalid key type can sneak in.

**Comment by LucasVanDongen** [comment]
So I went over some crash logs in Xcode instead of relying on Crashlytics and I've found more than one crash related to Branch and _all of them_ happened starting from this retry block:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/5376434/61221640-382cec80-a719-11e9-816c-8bf250a6df66.png">

Not sure if the code on our side does something unexpected (like not calling on main?) or something weird happens once a request needs to be retried.

**Comment by echo-branch** [comment]
@LucasVanDongen That looks like a different issue.  I'm going to add this to our sprint.

**Comment by LucasVanDongen** [comment]
Thanks a lot @echo-branch ! It's not happening to that many users but still a hard crash for the ones that do suffer. Did you create a separate story for this already?

**Comment by echo-branch** [comment]
@LucasVanDongen We have an internal ticket for it.

**Comment by leandromperez** [comment]
We're still experiencing this crash. Bellow, there's a part of one of the many stack traces.
Any ideas?
Thanks!

```

#9. Crashed: com.apple.root.user-initiated-qos
0  libobjc.A.dylib                0x1892e4d70 objc_msgSend + 16
1  Branch                         0x1014432e4 +[BNCEncodingUtils sanitizedStringFromString:] + 145 (BNCEncodingUtils.m:145)
2  Branch                         0x1014438f0 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 208 (BNCEncodingUtils.m:208)
3  Branch                         0x1014436f0 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 185 (BNCEncodingUtils.m:185)
4  Branch                         0x101443494 +[BNCEncodingUtils encodeDictionaryToJsonData:] + 159 (BNCEncodingUtils.m:159)
5  Branch                         0x101453290 -[BNCServerInterface preparePostRequest:url:key:retryNumber:] + 759 (BNCServerInterface.m:759)
6  Branch                         0x101451a90 -[BNCServerInterface postRequest:url:retryNumber:key:callback:] + 504 (BNCServerInterface.m:504)
7  Branch                         0x1014518c8 -[BNCServerInterface postRequest:url:key:callback:] + 481 (BNCServerInterface.m:481)
8  Branch                         0x101472154 -[BranchEventRequest makeRequest:key:callback:] + 64 (BranchEvent.m:64)
9  Branch                         0x101469974 __30-[Branch processNextQueueItem]_block_invoke_3 + 2088 (Branch.m:2088)
10 libdispatch.dylib              0x189b356c8 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x189b36484 _dispatch_client_callout + 16
12 libdispatch.dylib              0x189ae5b4c _dispatch_root_queue_drain + 684
13 libdispatch.dylib              0x189ae62c0 _dispatch_worker_thread2 + 128
14 libsystem_pthread.dylib        0x189d1917c _pthread_wqthread + 472
15 libsystem_pthread.dylib        0x189d1bcec start_wqthread + 4
```

**Comment by echo-branch** [comment]
Are you able to confirm these are new crashes and not crashes logged before the update, maybe check timestamps?  The symbolicated line numbers are the same in the two examples, and I would have expected them to be a little different in the encodeDictionaryToJsonString.

**Comment by leandromperez** [comment]
Yes I am, that piece of the stack I sent was from:

**# Date:** 2019-08-08T17:46:00Z

**Branch Version:**
  - Branch (0.27.1):
    - Branch/Core (= 0.27.1)


**Here's another one:**
```
# Date: 2019-08-08T00:55:00Z
# OS Version: 12.4.0 (16G77)
# Device: iPhone X
# RAM Free: 6%
# Disk Free: 8.7%

#6. Crashed: com.apple.root.user-initiated-qos
0  libobjc.A.dylib                0x194983530 objc_msgSend + 16
1  Branch                         0x1052bf280 +[BNCEncodingUtils sanitizedStringFromString:] + 145 (BNCEncodingUtils.m:145)
2  Branch                         0x1052bf908 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 215 (BNCEncodingUtils.m:215)
3  Branch                         0x1052bf8e4 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 192 (BNCEncodingUtils.m:192)
4  Branch                         0x1052bf430 +[BNCEncodingUtils encodeDictionaryToJsonData:] + 159 (BNCEncodingUtils.m:159)
5  Branch                         0x1052cf300 -[BNCServerInterface preparePostRequest:url:key:retryNumber:] + 777 (BNCServerInterface.m:777)
6  Branch                         0x1052cdaac -[BNCServerInterface postRequest:url:retryNumber:key:callback:] + 504 (BNCServerInterface.m:504)
7  Branch                         0x1052cd8e4 -[BNCServerInterface postRequest:url:key:callback:] + 481 (BNCServerInterface.m:481)
8  Branch                         0x1052ee108 -[BranchEventRequest makeRequest:key:callback:] + 64 (BranchEvent.m:64)
9  Branch                         0x1052e5928 __30-[Branch processNextQueueItem]_block_invoke_3 + 2086 (Branch.m:2086)
10 libdispatch.dylib              0x1951d0a38 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1951d17d4 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1951b4afc _dispatch_root_queue_drain + 636
13 libdispatch.dylib              0x1951b5248 _dispatch_worker_thread2 + 116
14 libsystem_pthread.dylib        0x1953b21b4 _pthread_wqthread + 464
15 libsystem_pthread.dylib        0x1953b4cd4 start_wqthread + 4
```

**Comment by echo-branch** [comment]
Looks like I'll have to reopen and add this to our next sprint.  Thanks for letting us know this issue still exists.

**Comment by leandromperez** [comment]
Hi,
Any news on this issue? Our users are still experiencing this in:
  - Branch (0.27.1):
  - Branch/Core (= 0.27.1)
Thanks!

**Comment by echo-branch** [comment]
Hi,

Unfortunately this ticket slipped from our last sprint.  Hoping to get it this sprint.

**Comment by echo-branch** [comment]
@leandromperez Finally found some time to devote to this.  

Could you provide a little more information about your app.  Does it include any C/C++ code?  Maybe a section of code where you manage your own memory?  

The only way I could get a similar crash is by forcing a deallocation of NSString, but that's a very odd example.

**Comment by leandromperez** [comment]
Hi,
No, we don't include any C/C++ code and we don't manage or own memory.

It always happens on a `com.apple.root.user-initiated-qos` thread.

I just went through most of our crashes related to this issue. These are the different in stack traces I could gather:

1. 
```
0  libobjc.A.dylib                0x18b087530 objc_msgSend + 16
1  Branch                         0x1037a3280 +[BNCEncodingUtils sanitizedStringFromString:] + 145 (BNCEncodingUtils.m:145)
2  Branch                         0x1037a3908 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 215 (BNCEncodingUtils.m:215)
3  Branch                         0x1037a38e4 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 192 (BNCEncodingUtils.m:192)
4  Branch                         0x1037a3430 +[BNCEncodingUtils encodeDictionaryToJsonData:] + 159 (BNCEncodingUtils.m:159)
5  Branch                         0x1037b3300 -[BNCServerInterface preparePostRequest:url:key:retryNumber:] + 777 (BNCServerInterface.m:777)
6  Branch                         0x1037b1aac -[BNCServerInterface postRequest:url:retryNumber:key:callback:] + 504 (BNCServerInterface.m:504)
7  Branch                         0x1037b18e4 -[BNCServerInterface postRequest:url:key:callback:] + 481 (BNCServerInterface.m:481)
8  Branch                         0x1037d2108 -[BranchEventRequest makeRequest:key:callback:] + 64 (BranchEvent.m:64)
9  Branch                         0x1037c9928 __30-[Branch processNextQueueItem]_block_invoke_3 + 2086 (Branch.m:2086)
10 libdispatch.dylib              0x18b8d4a38 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x18b8d57d4 _dispatch_client_callout + 16
12 libdispatch.dylib              0x18b886164 _dispatch_root_queue_drain + 680
13 libdispatch.dylib              0x18b8868d4 _dispatch_worker_thread2 + 128
14 libsystem_pthread.dylib        0x18bab61b4 _pthread_wqthread + 464
15 libsystem_pthread.dylib        0x18bab8cd4 start_wqthread + 4
```
2.
```
0  libobjc.A.dylib                0x1be9e7530 objc_msgSend + 16
1  Branch                         0x102e6f280 +[BNCEncodingUtils sanitizedStringFromString:] + 145 (BNCEncodingUtils.m:145)
2  Branch                         0x102e6f908 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 215 (BNCEncodingUtils.m:215)
3  Branch                         0x102e6f8e4 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 192 (BNCEncodingUtils.m:192)
4  Branch                         0x102e6f430 +[BNCEncodingUtils encodeDictionaryToJsonData:] + 159 (BNCEncodingUtils.m:159)
5  Branch                         0x102e7f300 -[BNCServerInterface preparePostRequest:url:key:retryNumber:] + 777 (BNCServerInterface.m:777)
6  Branch                         0x102e7daac -[BNCServerInterface postRequest:url:retryNumber:key:callback:] + 504 (BNCServerInterface.m:504)
7  Branch                         0x102e7d8e4 -[BNCServerInterface postRequest:url:key:callback:] + 481 (BNCServerInterface.m:481)
8  Branch                         0x102eb0064 -[BranchUserCompletedActionRequest makeRequest:key:callback:] + 63 (BranchUserCompletedActionRequest.m:63)
9  Branch                         0x102e95928 __30-[Branch processNextQueueItem]_block_invoke_3 + 2086 (Branch.m:2086)
10 libdispatch.dylib              0x1bf234a38 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1bf2357d4 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1bf218afc _dispatch_root_queue_drain + 636
13 libdispatch.dylib              0x1bf219248 _dispatch_worker_thread2 + 116
14 libsystem_pthread.dylib        0x1bf4161b4 _pthread_wqthread + 464
15 libsystem_pthread.dylib        0x1bf418cd4 start_wqthread + 4
```

3.
```
0  libobjc.A.dylib                0x1e59af6b0 objc_msgSend + 16
1  Branch                         0x105023280 +[BNCEncodingUtils sanitizedStringFromString:] + 145 (BNCEncodingUtils.m:145)
2  Branch                         0x105023908 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 215 (BNCEncodingUtils.m:215)
3  Branch                         0x1050238e4 +[BNCEncodingUtils encodeDictionaryToJsonString:] + 192 (BNCEncodingUtils.m:192)
4  Branch                         0x105023430 +[BNCEncodingUtils encodeDictionaryToJsonData:] + 159 (BNCEncodingUtils.m:159)
5  Branch                         0x105033300 -[BNCServerInterface preparePostRequest:url:key:retryNumber:] + 777 (BNCServerInterface.m:777)
6  Branch                         0x105032624 __75-[BNCServerInterface genericHTTPRequest:retryNumber:callback:retryHandler:]_block_invoke_2 + 567 (BNCServerInterface.m:567)
7  libdispatch.dylib              0x1e61a1884 _dispatch_client_callout + 20
8  libdispatch.dylib              0x1e61a4880 _dispatch_continuation_pop + 408
9  libdispatch.dylib              0x1e61b4b00 _dispatch_source_invoke2 + 892
10 libdispatch.dylib              0x1e61b44a4 _dispatch_source_invoke + 432
11 libdispatch.dylib              0x1e61ad62c _dispatch_main_queue_callback_4CF + 740
12 CoreFoundation                 0x1e6722024 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13 CoreFoundation                 0x1e671ccd4 __CFRunLoopRun + 1888
14 CoreFoundation                 0x1e671c254 CFRunLoopRunSpecific + 452
15 GraphicsServices               0x1e895bd8c GSEventRunModal + 108
16 UIKitCore                      0x213a644c0 UIApplicationMain + 216
17 OurApp                         0x1042c7a64 main + 18 (main.swift:18)
18 libdyld.dylib                  0x1e61d8fd8 start + 4
```

**Comment by echo-branch** [comment]
Thanks for the additional information.  I'm unfortunately unable to report any progress on this at the moment.

**Comment by donnellyk** [comment]
We are also seeing this crash for a number of users, don't really have more information to add beyond that. It is happening in the first release where we include the Branch SDK, so its not a matter of older versions getting reported.

**Comment by csalmi-branch** [comment]
@donnellyk can you provide us a bit more information about your integration? Which SDK version are you using? Do you use any sort of hybrid C/C++ app or do any memory management of your app?

**Comment by donnellyk** [comment]
We are using mParticle Branch's integration, v7.11.0 
Looks like that uses v0.28.1 of the Branch SDK. 

We have a fairly straight-forward app w/ no direct C code or memory management. Some dependencies we use may though, I can not be sure: Firebase, mParticle are the biggest.

**Comment by donnellyk** [comment]
We do include the Firebase Performance Monitoring framework but currently have it disabled (due to this crash that since has been crashed but we never renabled it: https://github.com/firebase/firebase-ios-sdk/issues/2283)

**Comment by leandromperez** [comment]
FYI, 
We released a new build and the crash is still happening:

**OS:** iOS 13, iOS 12

**PODS:**
  - Alamofire (4.9.0)
  - AlamofireImage (3.5.2):
    - Alamofire (~> 4.8)
  - Amplitude-iOS (4.8.1)
  - Analytics (3.7.0)
  - apptentive-ios (5.2.7)
  - **Branch (0.28.1)**:
    - **Branch/Core (= 0.28.1)**
  - **Branch/Core (0.28.1)**
  - CleverTap-iOS-SDK (3.7.0):
    - SDWebImage (~> 5.1)
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - CTNotificationService (0.1.1)
  - Curry (4.0.2)
  - Differentiator (4.0.1)
  - Fabric (1.10.2)
  - Firebase/Core (6.9.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.1.2)
  - Firebase/CoreOnly (6.9.0):
    - FirebaseCore (= 6.3.0)
  - Firebase/Performance (6.9.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 3.1.4)
  - Firebase/RemoteConfig (6.9.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 4.4.1)
  - FirebaseABTesting (3.1.1):
    - FirebaseAnalyticsInterop (~> 1.3)
    - FirebaseCore (~> 6.1)
    - Protobuf (~> 3.8)
  - FirebaseAnalytics (6.1.2):
    - FirebaseCore (~> 6.3)
    - FirebaseInstanceID (~> 4.2)
    - GoogleAppMeasurement (= 6.1.2)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAnalyticsInterop (1.4.0)
  - FirebaseCore (6.3.0):
    - FirebaseCoreDiagnostics (~> 1.0)
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnostics (1.1.0):
    - FirebaseCoreDiagnosticsInterop (~> 1.0)
    - GoogleDataTransportCCTSupport (~> 1.0)
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/Logger (~> 6.2)
  - FirebaseCoreDiagnosticsInterop (1.0.0)
  - FirebaseInstanceID (4.2.5):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - FirebasePerformance (3.1.4):
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - FirebaseRemoteConfig (~> 4.4)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 6.2)
    - GoogleUtilities/ISASwizzler (~> 6.2)
    - GoogleUtilities/MethodSwizzler (~> 6.2)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.9)
  - FirebaseRemoteConfig (4.4.1):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (~> 3.9)
  - FSCalendar (2.8.0)
  - GoogleAppMeasurement (6.1.2):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - GoogleDataTransport (2.0.0)
  - GoogleDataTransportCCTSupport (1.1.0):
    - GoogleDataTransport (~> 2.0)
    - nanopb
  - GoogleToolboxForMac/Defines (2.2.1)
  - GoogleToolboxForMac/Logger (2.2.1):
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - "GoogleToolboxForMac/NSData+zlib (2.2.1)":
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - GoogleUtilities/AppDelegateSwizzler (6.3.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.3.0)
  - GoogleUtilities/ISASwizzler (6.3.0)
  - GoogleUtilities/Logger (6.3.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.3.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.3.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.3.0)"
  - GoogleUtilities/Reachability (6.3.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.3.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.2.2)
  - LifetimeTracker (1.6.2)
  - lottie-ios (3.1.3)
  - Moya (13.0.1):
    - Moya/Core (= 13.0.1)
  - Moya/Core (13.0.1):
    - Alamofire (~> 4.1)
    - Result (~> 4.1)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - Nimble (8.0.4)
  - Protobuf (3.9.2)
  - Quick (2.2.0)
  - R.swift (5.0.3):
    - R.swift.Library (~> 5.0.0)
  - R.swift.Library (5.0.1)
  - ReachabilitySwift (4.3.1)
  - Result (4.1.0)
  - RxBlocking (5.0.0):
    - RxSwift (~> 5)
  - RxBluetoothKit (5.3.0):
    - RxSwift (~> 5.0)
  - RxCocoa (5.0.0):
    - RxRelay (~> 5)
    - RxSwift (~> 5)
  - RxDataSources (4.0.1):
    - Differentiator (~> 4.0)
    - RxCocoa (~> 5.0)
    - RxSwift (~> 5.0)
  - RxFeedback (3.0.0):
    - RxCocoa (~> 5.0)
    - RxSwift (~> 5.0)
  - RxGesture (3.0.0):
    - RxCocoa (~> 5.0)
    - RxSwift (~> 5.0)
  - RxKeyboard (1.0.0):
    - RxCocoa (~> 5.0)
    - RxSwift (~> 5.0)
  - RxRelay (5.0.0):
    - RxSwift (~> 5)
  - RxSwift (5.0.0)
  - RxSwiftExt (5.1.1):
    - RxSwiftExt/Core (= 5.1.1)
    - RxSwiftExt/RxCocoa (= 5.1.1)
  - RxSwiftExt/Core (5.1.1):
    - RxSwift (~> 5.0)
  - RxSwiftExt/RxCocoa (5.1.1):
    - RxCocoa (~> 5.0)
    - RxSwiftExt/Core
  - SDWebImage (5.2.0):
    - SDWebImage/Core (= 5.2.0)
  - SDWebImage/Core (5.2.0)
  - Segment-Amplitude (2.0.0):
    - Amplitude-iOS (~> 4.0)
    - Analytics (~> 3.6)
  - Segment-Branch (0.1.18):
    - Analytics
    - Branch (~> 0.28.1)
  - Segment-CleverTap (1.1.1):
    - Analytics (~> 3.0)
    - CleverTap-iOS-SDK (~> 3.7.0)
  - SkyFloatingLabelTextField (3.7.0)
  - SnapKit (4.0.1)
  - Sourcery (0.17.0)
  - SwiftLint (0.35.0)
  - SwiftyAttributes (5.1.1)
  - SwiftyStoreKit (0.15.0)
  - SwiftyUserDefaults (4.0.0)

**Comment by leandromperez** [comment]
any news on this issue?

**Comment by echo-branch** [comment]
I'm still not able to repro this issue.  So I'm going to put in a blind fix attempt by adjusting a queue settings.

I've also got some time blocked out this sprint do more in depth stress tests on our persistence and loading code.

**Comment by echo-branch** [comment]
Released 0.30.0

Changed all queues to default priority.  As a hedge against Firebase performance crashes.
Fixed a serialization error on commerce event.  Though this only manifested as a nil in my testing.

These are blind fixes, since I can't reliably repro this issue.

**Comment by slccper** [comment]
hi

same problem in 0.30.0, any news?

 thanks.

**Comment by echo-branch** [comment]
@slccper  Do you happen to have reliable repro for this issue?  I've thus far been making rather blind attempts at a fix.

**Comment by slccper** [comment]
@echo-branch  it looks like they happen mostly when the app is in the background.

**Comment by Emiyazhang** [comment]
Our team’s app also encountered this problem。


Branch (0.34.0)

any news on this issue?



```
1 FutuNiuniu | +[BNCEncodingUtils sanitizedStringFromString:] (BNCEncodingUtils.m:145)
-- | --
2 FutuNiuniu | +[BNCEncodingUtils encodeDictionaryToJsonString:] (BNCEncodingUtils.m:215)
3 FutuNiuniu | +[BNCEncodingUtils encodeDictionaryToJsonString:] (BNCEncodingUtils.m:0)
4 FutuNiuniu | +[BNCEncodingUtils encodeDictionaryToJsonData:] (BNCEncodingUtils.m:0)
5 FutuNiuniu | -[BNCServerInterface preparePostRequest:url:key:retryNumber:] (BNCServerInterface.m:0)
6 FutuNiuniu | __75-[BNCServerInterface genericHTTPRequest:retryNumber:callback:retryHandler:]_block_invoke_2 (BNCServerInterface.m:0)
```

**Comment by ihsanhusnul** [comment]
Hi, I've reproduced this issue, CMIIW.
I think the culprit is the NSString pointer on https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BNCEncodingUtils.m#L215
<img width="1244" alt="Screen Shot 2020-08-27 at 13 49 43" src="https://user-images.githubusercontent.com/3015018/91431341-70927a00-e88a-11ea-8378-60e1ab6d5568.png">

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1054/files

**Comment by ihsanhusnul** [comment]
I'm not sure if this is relevant enough.
but I able to repro this issue by hardcoded [this line](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BNCServerInterface.m#L194) to force the method crashed to call.

I using v0.30.0 and still waiting for the fixes. since this crash is top of my apps. :(

**Comment by echo-branch** [comment]
@ihsanhusnul 
Thanks for the tip.  I'll try to repro it with your approach after this current sprint.

**Comment by benski** [comment]
We have the same intermittent crash in our app crash reporting.
@echo-branch I found a threading issue that likely is the root cause of this issue. I have submitted a PR that will fix the problem I identified and hopefully the crashes for everyone as well.

**Comment by echo-branch** [comment]
Merged and shipped potential fix by @benski. Closing for now.
